"""
process_model.py
================
A code-as-process-model framework for defining, validating, executing,
and generating representations of business processes.

Design principles:
  - The code IS the canonical process definition.
  - Gaps are NotImplementedError bodies or explicit raise_gap() calls.
  - WorkItems are first-class objects surfaced by validate().
  - Diagrams and reports are generated by reflecting on the class structure.
  - All actors, steps, and data objects are subclasses of typed base classes.

Usage:
  process = DocumentApprovalProcess()
  process.validate()           # surface gaps as WorkItems
  process.report()             # print gap report to stdout
  process.generate_mermaid()   # print a Mermaid flowchart to stdout
  process.run(context)         # execute the process with a real/mock context
"""

from __future__ import annotations

import inspect
import textwrap
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Optional, Type


# ---------------------------------------------------------------------------
# Work Item — the collaboration primitive
# ---------------------------------------------------------------------------

class WorkItemStatus(Enum):
    OPEN       = "open"
    PROPOSED   = "proposed"   # AI or human has suggested a resolution
    RESOLVED   = "resolved"
    WONT_FIX   = "wont_fix"


class WorkItemType(Enum):
    GAP            = "gap"            # missing logic / undefined path
    QUESTION       = "question"       # ambiguity requiring a decision
    ASSUMPTION     = "assumption"     # something assumed, needs confirmation
    IMPROVEMENT    = "improvement"    # optional enhancement


@dataclass
class WorkItem:
    """
    A gap, question, assumption, or improvement discovered in the process.

    Work items are raised by Steps, Actors, or DataObjects via raise_gap().
    They accumulate on the owning Process instance and form the collaboration
    backlog that human and AI agents work through together.
    """
    id: str
    type: WorkItemType
    description: str
    raised_by: str                        # class name that raised this item
    linked_to: str                        # class name of the related element
    status: WorkItemStatus = WorkItemStatus.OPEN
    owner: Optional[str] = None           # agent assigned to resolve it
    resolution: Optional[str] = None      # how it was resolved
    raised_at: datetime = field(default_factory=datetime.now)

    def resolve(self, resolution: str, owner: str = "human") -> None:
        """Mark this work item as resolved with a description of the resolution."""
        self.resolution = resolution
        self.owner = owner
        self.status = WorkItemStatus.RESOLVED

    def propose(self, proposal: str, owner: str = "ai_agent") -> None:
        """Record a proposed resolution, pending human review."""
        self.resolution = proposal
        self.owner = owner
        self.status = WorkItemStatus.PROPOSED

    def __str__(self) -> str:
        tag = f"[{self.type.value.upper()}]"
        status = f"({self.status.value})"
        owner = f" → {self.owner}" if self.owner else ""
        return f"  {self.id} {tag} {status}{owner}\n    {self.linked_to}: {self.description}"


# ---------------------------------------------------------------------------
# Event — the event-driven primitive
# ---------------------------------------------------------------------------

@dataclass
class Event:
    """
    An event raised by an actor or the system during process execution.

    Events decouple the producer of an action from its consumers — actors
    subscribe to events they are interested in and react via on_event().
    The payload carries any data the publisher wishes to share alongside
    the named event; consumers should prefer the shared context dict for
    structured process state.
    """

    name: str
    source: str                            # Actor.name or "System" that raised this event
    payload: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)

    def __str__(self) -> str:
        return (
            f"Event({self.name!r}, source={self.source!r}, "
            f"at={self.timestamp.strftime('%H:%M:%S')})"
        )


class EventBus:
    """
    Simple synchronous event bus for routing events between actors.

    Actors register interest in named events via subscribe().  When an
    event is published, every subscribed actor's on_event() method is
    called in registration order.  The shared process context dict is
    threaded through each handler so that side-effects accumulate.

    Usage::

        bus = EventBus()
        bus.subscribe("document_submitted", system_actor_instance)
        context = bus.publish(Event("document_submitted", "Author"), context)
    """

    def __init__(self) -> None:
        self._subscribers: dict[str, list[Actor]] = {}
        self._history: list[Event] = []

    def subscribe(self, event_name: str, actor: Actor) -> None:
        """Register *actor* to receive events whose name matches *event_name*."""
        self._subscribers.setdefault(event_name, []).append(actor)

    def publish(self, event: Event, context: dict[str, Any]) -> dict[str, Any]:
        """
        Dispatch *event* to all subscribed actors.

        Each subscriber's on_event() is called in registration order.
        Returns the (possibly modified) context after all handlers run.
        Actors that have not implemented on_event() raise NotImplementedError,
        which is surfaced here so callers can react accordingly.
        """
        self._history.append(event)
        print(f"  [EVENT] {event.name} (source: {event.source})")
        for actor in self._subscribers.get(event.name, []):
            context = actor.on_event(event, self, context)
        return context

    @property
    def history(self) -> list[Event]:
        """Return a copy of every event published so far, in order."""
        return list(self._history)


# ---------------------------------------------------------------------------
# Process — the orchestrator and collaboration surface
# ---------------------------------------------------------------------------

class Process(ABC):
    """
    Base class for all processes.

    A Process owns the ordered list of Steps, the participating Actors,
    and the accumulated WorkItems discovered during validation or execution.

    Subclasses define:
      - actors()  → list of Actor subclasses involved
      - steps()   → ordered list of Step subclasses in this process
      - name      → human-readable process name
      - description → what this process achieves
    """

    name: str = "Unnamed Process"
    description: str = ""

    def __init__(self) -> None:
        self._work_items: list[WorkItem] = []
        self._work_item_counter: int = 0

    # -- Subclass contract ---------------------------------------------------

    @abstractmethod
    def actors(self) -> list[Type[Actor]]:
        """Return the Actor subclasses that participate in this process."""
        ...

    @abstractmethod
    def steps(self) -> list[Type[Step]]:
        """Return the Step subclasses in execution order."""
        ...

    # -- Work item management ------------------------------------------------

    def raise_gap(
        self,
        description: str,
        raised_by: str,
        linked_to: str,
        type: WorkItemType = WorkItemType.GAP,
    ) -> WorkItem:
        """Create and register a new work item on this process."""
        self._work_item_counter += 1
        wi = WorkItem(
            id=f"WI-{self._work_item_counter:03d}",
            type=type,
            description=description,
            raised_by=raised_by,
            linked_to=linked_to,
        )
        self._work_items.append(wi)
        return wi

    @property
    def work_items(self) -> list[WorkItem]:
        return list(self._work_items)

    @property
    def open_work_items(self) -> list[WorkItem]:
        return [wi for wi in self._work_items if wi.status == WorkItemStatus.OPEN]

    # -- Validation ----------------------------------------------------------

    def validate(self) -> list[WorkItem]:
        """
        Reflect on all Steps and Actors to surface structural gaps.

        Checks performed:
          - Steps with no defined actor
          - Steps with no inputs or no outputs
          - Steps whose handle() body raises NotImplementedError
          - Steps with no preconditions defined (assumption raised)
          - Steps with no postconditions defined (assumption raised)
          - Actors with no steps assigned to them
          - DataObject states with no transitions defined
        """
        self._work_items.clear()
        self._work_item_counter = 0

        actor_classes = self.actors()
        step_classes = self.steps()

        # Track which actors have at least one step
        actors_with_steps: set[str] = set()

        for step_cls in step_classes:
            sname = step_cls.__name__

            # Actor assigned?
            if not step_cls.actor:
                self.raise_gap(
                    f"No actor assigned — who is responsible for this step?",
                    raised_by="Process.validate",
                    linked_to=sname,
                )
            else:
                actors_with_steps.add(step_cls.actor.__name__)

            # Inputs defined?
            if not step_cls.inputs:
                self.raise_gap(
                    f"No inputs defined — what data does this step consume?",
                    raised_by="Process.validate",
                    linked_to=sname,
                )

            # Outputs defined?
            if not step_cls.outputs:
                self.raise_gap(
                    f"No outputs defined — what data does this step produce?",
                    raised_by="Process.validate",
                    linked_to=sname,
                )

            # Preconditions?
            if not step_cls.preconditions:
                self.raise_gap(
                    f"No preconditions defined — what must be true before this step runs?",
                    raised_by="Process.validate",
                    linked_to=sname,
                    type=WorkItemType.ASSUMPTION,
                )

            # Postconditions?
            if not step_cls.postconditions:
                self.raise_gap(
                    f"No postconditions defined — what must be true after this step completes?",
                    raised_by="Process.validate",
                    linked_to=sname,
                    type=WorkItemType.ASSUMPTION,
                )

            # handle() implemented?
            if _is_not_implemented(step_cls, "handle"):
                self.raise_gap(
                    f"handle() is not implemented — process logic is missing.",
                    raised_by="Process.validate",
                    linked_to=sname,
                )

            # Error paths?
            if _is_not_implemented(step_cls, "on_error"):
                self.raise_gap(
                    f"on_error() is not implemented — what happens if this step fails?",
                    raised_by="Process.validate",
                    linked_to=sname,
                )

        # Actors with no steps
        for actor_cls in actor_classes:
            if actor_cls.__name__ not in actors_with_steps:
                # An actor with event subscriptions participates via on_event(),
                # not necessarily via Steps — only raise the question when the
                # actor has neither steps nor subscriptions.
                if not getattr(actor_cls, "subscriptions", []):
                    self.raise_gap(
                        f"Actor has no steps assigned — is this role needed?",
                        raised_by="Process.validate",
                        linked_to=actor_cls.__name__,
                        type=WorkItemType.QUESTION,
                    )

        # Event-driven: actors with subscriptions but missing on_event()
        for actor_cls in actor_classes:
            if getattr(actor_cls, "subscriptions", []):
                if _is_not_implemented(actor_cls, "on_event"):
                    self.raise_gap(
                        "on_event() is not implemented — actor cannot respond to events.",
                        raised_by="Process.validate",
                        linked_to=actor_cls.__name__,
                    )

        return self.work_items

    # -- Execution -----------------------------------------------------------

    def run(self, context: dict[str, Any]) -> dict[str, Any]:
        """
        Execute the process steps in order against a context dictionary.

        The context acts as the shared data bus — steps read from it and
        write their outputs back to it.  In a real implementation each Step
        would also receive typed DataObject instances.
        """
        print(f"\n▶ Running: {self.name}")
        print("─" * 60)
        for step_cls in self.steps():
            step = step_cls(process=self)
            print(f"  → {step_cls.__name__}")
            try:
                context = step.execute(context)
            except NotImplementedError:
                print(f"     ⚠ NotImplementedError — step not yet implemented, skipping.")
            except Exception as exc:
                print(f"     ✗ Error: {exc}")
                try:
                    context = step.on_error(context, exc)
                except NotImplementedError:
                    print(f"     ⚠ on_error() not implemented — halting process.")
                    break
        print("─" * 60)
        print(f"✓ Process complete.\n")
        return context

    # -- Reporting -----------------------------------------------------------

    def report(self) -> None:
        """Print a human-readable gap report to stdout."""
        items = self.work_items
        if not items:
            self.validate()
            items = self.work_items

        open_items   = [wi for wi in items if wi.status == WorkItemStatus.OPEN]
        proposed     = [wi for wi in items if wi.status == WorkItemStatus.PROPOSED]
        resolved     = [wi for wi in items if wi.status == WorkItemStatus.RESOLVED]

        print(f"\n{'═'*60}")
        print(f"  PROCESS REVIEW REPORT: {self.name}")
        print(f"  {self.description}")
        print(f"{'═'*60}")
        print(f"  Steps:       {len(self.steps())}")
        print(f"  Actors:      {len(self.actors())}")
        print(f"  Work items:  {len(items)}  "
              f"(open: {len(open_items)}, proposed: {len(proposed)}, resolved: {len(resolved)})")
        print(f"{'─'*60}")

        by_type = {}
        for wi in items:
            by_type.setdefault(wi.type, []).append(wi)

        for wtype, wis in by_type.items():
            print(f"\n  {wtype.value.upper()}S ({len(wis)})")
            for wi in wis:
                print(str(wi))

        print(f"\n{'═'*60}\n")

    # -- Diagram generation --------------------------------------------------

    def generate_mermaid(self) -> str:
        """
        Generate a Mermaid flowchart string from the step definitions.

        The diagram is derived entirely from the class structure — no
        manual diagram maintenance is needed.  Re-run after any change
        to the process steps to get an updated diagram.
        """
        lines = ["flowchart TD"]
        lines.append(f'    %% {self.name}')
        lines.append(f'    START([Start]) --> {self.steps()[0].__name__}')

        step_classes = self.steps()
        for i, step_cls in enumerate(step_classes):
            sname  = step_cls.__name__
            label  = _camel_to_label(sname)
            actor  = step_cls.actor.__name__ if step_cls.actor else "Unassigned"
            inputs  = ", ".join(c.__name__ for c in step_cls.inputs)  if step_cls.inputs  else "—"
            outputs = ", ".join(c.__name__ for c in step_cls.outputs) if step_cls.outputs else "—"
            not_impl = _is_not_implemented(step_cls, "handle")

            shape_open  = "{{" if not_impl else "["
            shape_close = "}}" if not_impl else "]"

            lines.append(
                f'    {sname}{shape_open}"{label}<br/>'
                f'<small>{actor}</small>"{shape_close}'
            )
            lines.append(f'    %% inputs: {inputs} | outputs: {outputs}')

            if i < len(step_classes) - 1:
                next_cls = step_classes[i + 1]
                lines.append(f'    {sname} --> {next_cls.__name__}')

        lines.append(f'    {step_classes[-1].__name__} --> END([End])')

        # Swim-lane comment block
        lines.append("\n    %% Actor responsibilities:")
        for actor_cls in self.actors():
            assigned = [s.__name__ for s in step_classes if s.actor and s.actor.__name__ == actor_cls.__name__]
            if assigned:
                lines.append(f"    %% {actor_cls.__name__}: {', '.join(assigned)}")

        diagram = "\n".join(lines)
        return diagram

    def print_mermaid(self) -> None:
        """Print the Mermaid diagram to stdout, wrapped in a code fence."""
        print("\n```mermaid")
        print(self.generate_mermaid())
        print("```\n")

    def generate_event_mermaid(self) -> str:
        """
        Generate a Mermaid flowchart showing the event-driven actor flow.

        The diagram is derived from the Actor subclasses' ``subscriptions``
        and ``publishes`` class attributes.  Edges represent events flowing
        between actors; node shape indicates whether on_event() is implemented.
        """
        lines = ["flowchart TD"]
        lines.append(f'    %% {self.name} — Event-Driven Flow')

        actor_classes = self.actors()

        lines.append(f'    START([External Request])')
        lines.append(f'    END([Process Complete])')

        # Build a lookup: event_name → list of actor classes that publish it
        publishers: dict[str, list[Type[Actor]]] = {}
        for actor_cls in actor_classes:
            for event_name in getattr(actor_cls, "publishes", []):
                publishers.setdefault(event_name, []).append(actor_cls)

        # Emit actor nodes
        for actor_cls in actor_classes:
            aname = actor_cls.__name__
            label = actor_cls.name
            not_impl = _is_not_implemented(actor_cls, "on_event")
            shape_open  = "{{" if not_impl else "["
            shape_close = "}}" if not_impl else "]"
            subs = getattr(actor_cls, "subscriptions", [])
            pubs = getattr(actor_cls, "publishes", [])
            subs_txt = ", ".join(subs) if subs else "—"
            pubs_txt = ", ".join(pubs) if pubs else "—"
            lines.append(
                f'    {aname}{shape_open}"{label}<br/>'
                f'<small>subscribes: {subs_txt}</small>"{shape_close}'
            )
            lines.append(f'    %% publishes: {pubs_txt}')

        # Emit edges: for each subscription, trace the publisher
        for actor_cls in actor_classes:
            for event_name in getattr(actor_cls, "subscriptions", []):
                safe_label = event_name.replace('"', "'")
                pub_list = publishers.get(event_name, [])
                if pub_list:
                    for pub_cls in pub_list:
                        lines.append(
                            f'    {pub_cls.__name__} -->|"{safe_label}"| {actor_cls.__name__}'
                        )
                else:
                    # No actor publishes this event — it originates externally
                    lines.append(
                        f'    START -->|"{safe_label}"| {actor_cls.__name__}'
                    )

        diagram = "\n".join(lines)
        return diagram

    def print_event_mermaid(self) -> None:
        """Print the event-driven Mermaid diagram to stdout, wrapped in a code fence."""
        print("\n```mermaid")
        print(self.generate_event_mermaid())
        print("```\n")

    # -- Event-driven execution ----------------------------------------------

    def register_actors(self, bus: EventBus) -> None:
        """
        Instantiate each actor and register it with *bus* for every event
        it declares in its ``subscriptions`` class attribute.
        """
        for actor_cls in self.actors():
            subs = getattr(actor_cls, "subscriptions", [])
            if subs:
                actor = actor_cls()
                for event_name in subs:
                    bus.subscribe(event_name, actor)

    def run_event_driven(
        self,
        initial_event: Event,
        context: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Execute the process in event-driven mode.

        Registers all actors with a fresh EventBus, then publishes
        *initial_event* to start the chain.  Actors handle events and
        publish further events, driving the process forward without
        central step-by-step orchestration.

        The shared *context* dict accumulates process state as events
        propagate — actors read from it and write their outputs back.
        """
        bus = EventBus()
        self.register_actors(bus)
        print(f"\n▶ Running (event-driven): {self.name}")
        print("─" * 60)
        try:
            context = bus.publish(initial_event, context)
        except NotImplementedError as exc:
            print(f"     ⚠ NotImplementedError — {exc}")
        except Exception as exc:
            print(f"     ✗ Unhandled error: {exc}")
        print("─" * 60)
        print(f"✓ Event-driven process complete.\n")
        return context


# ---------------------------------------------------------------------------
# Actor base class
# ---------------------------------------------------------------------------

class Actor(ABC):
    """
    Base class for all actors (roles) in a process.

    An actor represents a role, not a specific person.  The same person
    may fill multiple roles; multiple people may fill the same role.

    Subclasses define:
      - name          → display name of the role
      - description   → what this role is responsible for in the process
      - subscriptions → list of event names this actor reacts to
      - publishes     → list of event names this actor can raise
      - perform()     → dispatch a named action this actor can carry out
      - on_event()    → handle an inbound event from the EventBus
    """

    name: str = "Unnamed Actor"
    description: str = ""
    subscriptions: list[str] = []   # Event names this actor subscribes to
    publishes: list[str] = []       # Event names this actor may publish

    def perform(self, action: str, context: dict[str, Any]) -> dict[str, Any]:
        """
        Dispatch an action for this actor.

        Override in subclasses to implement actor-specific behaviour.
        Raise NotImplementedError for actions not yet defined.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__}.perform('{action}') is not implemented."
        )

    def notify(self, message: str, context: dict[str, Any]) -> None:
        """
        Send a notification to this actor.

        Override to implement email, Slack, in-app notification, etc.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__}.notify() is not implemented."
        )

    def on_event(self, event: Event, bus: EventBus, context: dict[str, Any]) -> dict[str, Any]:
        """
        Handle an event received from the EventBus.

        Override in subclasses to implement event-driven actor behaviour.
        The actor may read from and write to the shared *context* dict, and
        may publish new events via *bus* to trigger downstream actors.

        Raise NotImplementedError to mark this handler as an open gap.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__}.on_event('{event.name}') is not implemented."
        )


# ---------------------------------------------------------------------------
# DataObject base class
# ---------------------------------------------------------------------------

class DataObject(ABC):
    """
    Base class for all data objects that flow through a process.

    A DataObject has a state machine: a defined set of states and valid
    transitions between them.  Attempts to make an invalid transition
    raise a ValueError, enforcing process integrity.

    Subclasses define:
      - states           → Enum class of valid states
      - initial_state    → the state a new instance starts in
      - valid_transitions → dict mapping each state to the states it can move to
    """

    states: Type[Enum]
    initial_state: Enum
    valid_transitions: dict[Enum, list[Enum]] = {}

    def __init__(self) -> None:
        self._state = self.initial_state
        self._history: list[tuple[Enum, datetime]] = [(self._state, datetime.now())]

    @property
    def state(self) -> Enum:
        return self._state

    def transition(self, new_state: Enum) -> None:
        """
        Move this object to a new state, validating the transition first.

        Raises ValueError if the transition is not permitted.
        """
        allowed = self.valid_transitions.get(self._state, [])
        if new_state not in allowed:
            raise ValueError(
                f"Invalid transition on {self.__class__.__name__}: "
                f"{self._state.value} → {new_state.value}. "
                f"Allowed: {[s.value for s in allowed]}"
            )
        self._state = new_state
        self._history.append((new_state, datetime.now()))

    @property
    def history(self) -> list[tuple[Enum, datetime]]:
        return list(self._history)


# ---------------------------------------------------------------------------
# Step base class
# ---------------------------------------------------------------------------

class Step(ABC):
    """
    Base class for all process steps.

    A Step is a discrete unit of work performed by one Actor, consuming
    defined inputs and producing defined outputs.  Pre- and post-conditions
    document the invariants that must hold around the step.

    Class-level attributes (set on subclasses, not instances):
      - actor           → the Actor subclass responsible for this step
      - inputs          → list of DataObject subclasses consumed
      - outputs         → list of DataObject subclasses produced
      - preconditions   → list of plain-English strings
      - postconditions  → list of plain-English strings
      - description     → what this step does

    Instance methods:
      - handle()   → the step's core logic (raise NotImplementedError if not yet defined)
      - on_error() → what to do if handle() raises an exception
    """

    actor: Optional[Type[Actor]] = None
    inputs:  list[Type[DataObject]] = []
    outputs: list[Type[DataObject]] = []
    preconditions:  list[str] = []
    postconditions: list[str] = []
    description: str = ""

    def __init__(self, process: Process) -> None:
        self.process = process

    def execute(self, context: dict[str, Any]) -> dict[str, Any]:
        """
        Run the step: check preconditions, call handle(), check postconditions.
        """
        self._check_preconditions(context)
        context = self.handle(context)
        self._check_postconditions(context)
        return context

    @abstractmethod
    def handle(self, context: dict[str, Any]) -> dict[str, Any]:
        """
        Core step logic.  Receives and returns the shared process context.

        Raise NotImplementedError if this step is not yet implemented —
        that signals a gap to validate() and run().
        """
        raise NotImplementedError(
            f"{self.__class__.__name__}.handle() is not yet implemented."
        )

    def on_error(self, context: dict[str, Any], error: Exception) -> dict[str, Any]:
        """
        Error handler called when handle() raises an exception.

        Override to implement retry logic, compensation steps, escalation, etc.
        Raise NotImplementedError to mark this as an open gap.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__}.on_error() is not yet implemented."
        )

    def _check_preconditions(self, context: dict[str, Any]) -> None:
        """Override to add runtime precondition assertions."""
        pass

    def _check_postconditions(self, context: dict[str, Any]) -> None:
        """Override to add runtime postcondition assertions."""
        pass


# ===========================================================================
# DOCUMENT APPROVAL PROCESS
# ===========================================================================
# Below is a concrete process model for: User creates a document → approval
# workflow → published with access controls.
#
# Deliberate gaps are present (NotImplementedError / missing definitions) to
# demonstrate the validation and work-item system.  These are the starting
# point for collaborative resolution with an AI or human agent.
# ===========================================================================


# ---------------------------------------------------------------------------
# Data Objects
# ---------------------------------------------------------------------------

class DocumentState(Enum):
    DRAFT      = "draft"
    SUBMITTED  = "submitted"
    IN_REVIEW  = "in_review"
    APPROVED   = "approved"
    REJECTED   = "rejected"
    PUBLISHED  = "published"
    ARCHIVED   = "archived"


class Document(DataObject):
    """
    The core content artefact flowing through the approval process.

    Carries the content, metadata, and current workflow state.  State
    transitions are strictly validated to prevent process bypasses.
    """

    states = DocumentState
    initial_state = DocumentState.DRAFT
    valid_transitions = {
        DocumentState.DRAFT:      [DocumentState.SUBMITTED],
        DocumentState.SUBMITTED:  [DocumentState.IN_REVIEW, DocumentState.DRAFT],
        DocumentState.IN_REVIEW:  [DocumentState.APPROVED, DocumentState.REJECTED],
        DocumentState.APPROVED:   [DocumentState.PUBLISHED],
        DocumentState.REJECTED:   [DocumentState.DRAFT],
        DocumentState.PUBLISHED:  [DocumentState.ARCHIVED],
        # GAP: Can a published document be re-submitted for revision?
        #      If so, PUBLISHED → DRAFT should be added here.
        DocumentState.ARCHIVED:   [],
    }

    def __init__(self, title: str = "", content: str = "") -> None:
        super().__init__()
        self.title = title
        self.content = content
        self.author: Optional[str] = None
        self.approver: Optional[str] = None
        self.rejection_reason: Optional[str] = None
        self.version: int = 1


class AccessPolicyLevel(Enum):
    PUBLIC       = "public"
    INTERNAL     = "internal"
    RESTRICTED   = "restricted"
    CONFIDENTIAL = "confidential"


class AccessPolicy(DataObject):
    """
    Defines who can read a published document.

    Decoupled from the Document itself so access rules can be updated
    independently of document content.
    """

    states = AccessPolicyLevel
    initial_state = AccessPolicyLevel.INTERNAL
    valid_transitions = {
        # Any level can be changed to any other — access policy is mutable.
        AccessPolicyLevel.PUBLIC:       [AccessPolicyLevel.INTERNAL, AccessPolicyLevel.RESTRICTED, AccessPolicyLevel.CONFIDENTIAL],
        AccessPolicyLevel.INTERNAL:     [AccessPolicyLevel.PUBLIC, AccessPolicyLevel.RESTRICTED, AccessPolicyLevel.CONFIDENTIAL],
        AccessPolicyLevel.RESTRICTED:   [AccessPolicyLevel.PUBLIC, AccessPolicyLevel.INTERNAL, AccessPolicyLevel.CONFIDENTIAL],
        AccessPolicyLevel.CONFIDENTIAL: [AccessPolicyLevel.PUBLIC, AccessPolicyLevel.INTERNAL, AccessPolicyLevel.RESTRICTED],
    }

    def __init__(self) -> None:
        super().__init__()
        self.allowed_groups: list[str] = []
        self.allowed_users: list[str] = []
        # GAP: Is there an expiry date on access policies?
        self.expires_at: Optional[datetime] = None


class Notification(DataObject):
    """
    A notification dispatched to an Actor during the process.

    Tracks delivery status.  The notification system itself is a gap —
    see NotificationState transitions below.
    """

    class NotificationState(Enum):
        PENDING   = "pending"
        SENT      = "sent"
        DELIVERED = "delivered"
        FAILED    = "failed"
        # GAP: Should failed notifications be retried?  If so, add RETRYING state.

    states = NotificationState
    initial_state = NotificationState.PENDING
    valid_transitions = {
        NotificationState.PENDING:   [NotificationState.SENT, NotificationState.FAILED],
        NotificationState.SENT:      [NotificationState.DELIVERED, NotificationState.FAILED],
        NotificationState.DELIVERED: [],
        NotificationState.FAILED:    [],
    }

    def __init__(self, recipient: str = "", subject: str = "", body: str = "") -> None:
        super().__init__()
        self.recipient = recipient
        self.subject = subject
        self.body = body


# ---------------------------------------------------------------------------
# Actors
# ---------------------------------------------------------------------------

class AuthorActor(Actor):
    """
    The user who creates and submits documents for approval.

    Responsible for: creating drafts, editing rejected documents,
    and setting the initial access policy proposal.

    Event subscriptions:
      - document_creation_requested → create, edit, and submit a new draft
      - document_rejected           → revise draft and re-submit for approval
    """

    name = "Author"
    description = "Creates, edits, and submits documents for approval."
    subscriptions = ["document_creation_requested", "document_rejected"]
    publishes = ["document_submitted"]

    def perform(self, action: str, context: dict[str, Any]) -> dict[str, Any]:
        if action == "create_draft":
            doc = Document(
                title=context.get("title", "Untitled"),
                content=context.get("content", ""),
            )
            doc.author = context.get("user_id", "unknown")
            context["document"] = doc
            return context
        elif action == "edit_draft":
            doc: Document = context["document"]
            doc.content = context.get("new_content", doc.content)
            doc.version += 1
            return context
        elif action == "submit":
            doc: Document = context["document"]
            doc.transition(DocumentState.SUBMITTED)
            return context
        else:
            raise NotImplementedError(
                f"AuthorActor.perform('{action}') is not implemented."
            )

    def notify(self, message: str, context: dict[str, Any]) -> None:
        # GAP: Implement email / in-app notification to the author.
        raise NotImplementedError("AuthorActor.notify() is not implemented.")

    def on_event(self, event: Event, bus: EventBus, context: dict[str, Any]) -> dict[str, Any]:
        if event.name == "document_creation_requested":
            # Create the document draft
            context = self.perform("create_draft", context)
            print(f"     Document '{context['document'].title}' created (DRAFT).")
            # Edit and finalise the draft content
            context["new_content"] = context.get("content", "Document content goes here.")
            context = self.perform("edit_draft", context)
            print(f"     Draft edited (v{context['document'].version}).")
            # Submit the draft into the approval workflow
            context = self.perform("submit", context)
            print(f"     Document submitted for approval (SUBMITTED).")
            return bus.publish(Event("document_submitted", self.name), context)
        elif event.name == "document_rejected":
            doc: Document = context["document"]
            # Return the document to DRAFT state for revision
            doc.transition(DocumentState.DRAFT)
            context["new_content"] = context.get(
                "revised_content", context.get("content", "Revised document content.")
            )
            context = self.perform("edit_draft", context)
            print(f"     Draft revised after rejection (v{doc.version}).")
            # Re-submit the revised draft
            context = self.perform("submit", context)
            print(f"     Revised document re-submitted for approval (SUBMITTED).")
            return bus.publish(Event("document_submitted", self.name), context)
        else:
            raise NotImplementedError(
                f"AuthorActor.on_event('{event.name}') is not implemented."
            )


class ApproverActor(Actor):
    """
    A designated reviewer who approves or rejects submitted documents.

    Responsible for: reviewing document content, checking compliance,
    approving or rejecting with a mandatory reason on rejection.

    Open questions:
      - How is an approver assigned? (role-based, document-category, manual)
      - What is the SLA for approval? (see WI-004 equivalent in validate())
      - Can an approver delegate to another approver?

    Event subscriptions:
      - document_assigned_for_review → review the document; publish
        document_approved or document_rejected based on the decision.
    """

    name = "Approver"
    description = "Reviews submitted documents and approves or rejects them."
    subscriptions = ["document_assigned_for_review"]
    publishes = ["document_approved", "document_rejected"]

    def perform(self, action: str, context: dict[str, Any]) -> dict[str, Any]:
        if action == "approve":
            doc: Document = context["document"]
            doc.approver = context.get("approver_id", "unknown")
            doc.transition(DocumentState.APPROVED)
            return context
        elif action == "reject":
            doc: Document = context["document"]
            reason = context.get("rejection_reason")
            if not reason:
                raise ValueError("A rejection reason is required.")
            doc.rejection_reason = reason
            doc.transition(DocumentState.REJECTED)
            return context
        elif action == "request_changes":
            # GAP: 'request_changes' is a common workflow state between
            # IN_REVIEW and REJECTED — should it be a distinct step/state?
            raise NotImplementedError(
                "ApproverActor.perform('request_changes') is not implemented."
            )
        else:
            raise NotImplementedError(
                f"ApproverActor.perform('{action}') is not implemented."
            )

    def notify(self, message: str, context: dict[str, Any]) -> None:
        # GAP: Implement notification — email, Slack, or workflow system.
        raise NotImplementedError("ApproverActor.notify() is not implemented.")

    def on_event(self, event: Event, bus: EventBus, context: dict[str, Any]) -> dict[str, Any]:
        if event.name == "document_assigned_for_review":
            doc: Document = context["document"]
            doc.transition(DocumentState.IN_REVIEW)
            decision = context.get("approval_decision", "approve")
            context["approver_id"] = context.get("approver_id", "approver_001")
            if decision == "approve":
                context = self.perform("approve", context)
                print(f"     Document APPROVED by {context['approver_id']}.")
                return bus.publish(Event("document_approved", self.name), context)
            elif decision == "reject":
                context["rejection_reason"] = context.get(
                    "rejection_reason", "Does not meet content standards."
                )
                context = self.perform("reject", context)
                print(f"     Document REJECTED: {context['rejection_reason']}")
                return bus.publish(Event("document_rejected", self.name), context)
            else:
                raise NotImplementedError(
                    f"ApproverActor.on_event: unknown decision '{decision}'."
                )
        else:
            raise NotImplementedError(
                f"ApproverActor.on_event('{event.name}') is not implemented."
            )


class SystemActor(Actor):
    """
    The intranet platform itself — performs automated steps.

    Responsible for: routing documents, applying access policies,
    sending system notifications, and publishing to the intranet.

    Event subscriptions:
      - document_submitted    → assign an approver and route for review.
      - access_policy_set     → publish the document with access controls.
    """

    name = "System"
    description = "Automated platform actions: routing, publishing, notifications."
    subscriptions = ["document_submitted", "access_policy_set"]
    publishes = ["document_assigned_for_review", "document_published"]

    def perform(self, action: str, context: dict[str, Any]) -> dict[str, Any]:
        if action == "route_to_approver":
            # GAP: Approver assignment logic is not defined.
            # Options: (a) category-based routing, (b) author nominates,
            # (c) round-robin from an approver pool.
            raise NotImplementedError(
                "SystemActor.perform('route_to_approver') — approver assignment not defined."
            )
        elif action == "publish":
            doc: Document = context["document"]
            doc.transition(DocumentState.PUBLISHED)
            context["published_url"] = f"/intranet/documents/{doc.title.lower().replace(' ', '-')}"
            return context
        elif action == "apply_access_policy":
            # GAP: How is the access policy linked to the intranet ACL system?
            raise NotImplementedError(
                "SystemActor.perform('apply_access_policy') is not implemented."
            )
        elif action == "archive":
            doc: Document = context["document"]
            doc.transition(DocumentState.ARCHIVED)
            return context
        else:
            raise NotImplementedError(
                f"SystemActor.perform('{action}') is not implemented."
            )

    def notify(self, message: str, context: dict[str, Any]) -> None:
        """Send a system notification. Stub — replace with real dispatch."""
        print(f"  [SYSTEM NOTIFICATION] {message}")

    def on_event(self, event: Event, bus: EventBus, context: dict[str, Any]) -> dict[str, Any]:
        if event.name == "document_submitted":
            # GAP: Approver assignment logic is not yet defined.
            # For now, use the approver_id already present in context (if any).
            assigned = context.get("approver_id", "approver_001")
            context["assigned_approver"] = assigned
            print(f"     Routing document to approver: {assigned}")
            return bus.publish(Event("document_assigned_for_review", self.name), context)
        elif event.name == "access_policy_set":
            context = self.perform("publish", context)
            print(f"     Document PUBLISHED at {context.get('published_url', 'unknown URL')}.")
            # GAP: apply_access_policy not yet implemented.
            # context = self.perform("apply_access_policy", context)
            return bus.publish(Event("document_published", self.name), context)
        else:
            raise NotImplementedError(
                f"SystemActor.on_event('{event.name}') is not implemented."
            )


class AdminActor(Actor):
    """
    An intranet administrator who manages access policies and handles escalations.

    Responsible for: setting access levels on published documents,
    managing user groups, and resolving approval escalations.

    GAP: The exact boundary between Approver and Admin responsibilities
    around access policy is not defined.  Does the Approver set the
    access level as part of approval, or does Admin set it post-publication?

    Event subscriptions:
      - document_approved → set the access policy for the approved document
        and publish access_policy_set to trigger publication.
    """

    name = "Admin"
    description = "Manages access policies, user groups, and escalations."
    subscriptions = ["document_approved"]
    publishes = ["access_policy_set"]

    def perform(self, action: str, context: dict[str, Any]) -> dict[str, Any]:
        raise NotImplementedError(
            f"AdminActor.perform('{action}') is not implemented."
        )

    def notify(self, message: str, context: dict[str, Any]) -> None:
        raise NotImplementedError("AdminActor.notify() is not implemented.")

    def on_event(self, event: Event, bus: EventBus, context: dict[str, Any]) -> dict[str, Any]:
        if event.name == "document_approved":
            # GAP: Access policy assignment logic is not yet defined.
            # For now, apply a default INTERNAL access policy.
            policy = AccessPolicy()
            context["access_policy"] = policy
            print(f"     Access policy set (default: INTERNAL).")
            return bus.publish(Event("access_policy_set", self.name), context)
        else:
            raise NotImplementedError(
                f"AdminActor.on_event('{event.name}') is not implemented."
            )


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------

class CreateDraft(Step):
    """
    Author creates a new document draft on the intranet.

    The author provides a title, initial content, and optionally proposes
    an access policy level.  The system assigns a document ID and sets
    the initial state to DRAFT.
    """

    actor = AuthorActor
    inputs:  list[Type[DataObject]] = []            # No prior document — this is the origin
    outputs: list[Type[DataObject]] = [Document]
    preconditions  = ["Author is authenticated.", "Author has 'create document' permission."]
    postconditions = ["Document exists in DRAFT state.", "Document has a unique ID."]
    description    = "Author creates a new document draft."

    def handle(self, context: dict[str, Any]) -> dict[str, Any]:
        author = AuthorActor()
        context = author.perform("create_draft", context)
        print(f"     Document '{context['document'].title}' created (DRAFT).")
        return context

    def on_error(self, context: dict[str, Any], error: Exception) -> dict[str, Any]:
        # GAP: What happens if document creation fails?
        # (e.g. storage unavailable, duplicate title, permission denied)
        raise NotImplementedError("CreateDraft.on_error() is not implemented.")


class EditAndFinaliseDraft(Step):
    """
    Author edits the draft until it is ready for submission.

    This step may loop — the author can save and return multiple times.
    It also covers re-editing after a rejection (the document returns to
    DRAFT state and the author must re-submit).

    GAP: How many revision cycles are permitted before escalation?
    """

    actor = AuthorActor
    inputs:  list[Type[DataObject]] = [Document]
    outputs: list[Type[DataObject]] = [Document]
    preconditions  = ["Document is in DRAFT state.", "Author is the document owner."]
    postconditions = ["Document content is non-empty.", "Document is ready for submission."]
    description    = "Author iteratively edits the draft to completion."

    def handle(self, context: dict[str, Any]) -> dict[str, Any]:
        # In a real implementation this would be an interactive editing session.
        # Here we simulate a single save.
        author = AuthorActor()
        context["new_content"] = context.get("content", "Document content goes here.")
        context = author.perform("edit_draft", context)
        print(f"     Draft edited (v{context['document'].version}).")
        return context

    def on_error(self, context: dict[str, Any], error: Exception) -> dict[str, Any]:
        # GAP: Handle auto-save failures, concurrent edit conflicts, etc.
        raise NotImplementedError("EditAndFinaliseDraft.on_error() is not implemented.")


class SubmitForApproval(Step):
    """
    Author submits the finalised draft into the approval workflow.

    The document transitions from DRAFT to SUBMITTED.  The system then
    routes it to the appropriate approver.

    GAP: Should the author be able to recall a submission (SUBMITTED → DRAFT)
    after it has been submitted but before review begins?
    """

    actor = AuthorActor
    inputs:  list[Type[DataObject]] = [Document]
    outputs: list[Type[DataObject]] = [Document, Notification]
    preconditions  = [
        "Document is in DRAFT state.",
        "Document has a non-empty title and content.",
        "Author confirms document is ready.",
    ]
    postconditions = [
        "Document is in SUBMITTED state.",
        "Approver has been notified.",
        "Submission timestamp is recorded.",
    ]
    description = "Author submits the draft document for approval review."

    def handle(self, context: dict[str, Any]) -> dict[str, Any]:
        author = AuthorActor()
        context = author.perform("submit", context)
        print(f"     Document submitted for approval (SUBMITTED).")
        # GAP: Route to approver — approver assignment logic not yet defined.
        # system = SystemActor()
        # context = system.perform("route_to_approver", context)
        return context

    def on_error(self, context: dict[str, Any], error: Exception) -> dict[str, Any]:
        # GAP: If submission fails, should the document revert to DRAFT automatically?
        raise NotImplementedError("SubmitForApproval.on_error() is not implemented.")


class ReviewDocument(Step):
    """
    Approver reviews the submitted document for content, accuracy, and compliance.

    The approver may: approve, reject (with mandatory reason), or request changes.

    GAP: 'Request changes' is a common real-world outcome not yet modelled
    as a distinct state/step.  Currently only approve/reject are handled.

    GAP: What is the SLA for completing a review?  What happens when it
    expires — escalation to Admin, automatic approval, or rejection?
    """

    actor = ApproverActor
    inputs:  list[Type[DataObject]] = [Document]
    outputs: list[Type[DataObject]] = [Document, Notification]
    preconditions  = [
        "Document is in SUBMITTED or IN_REVIEW state.",
        "An approver has been assigned.",
        "Approver has 'approve document' permission.",
    ]
    postconditions = [
        "Document is in APPROVED or REJECTED state.",
        "Approver identity and decision timestamp are recorded.",
        "Author has been notified of the outcome.",
    ]
    description = "Approver reviews the document and makes an approve/reject decision."

    def handle(self, context: dict[str, Any]) -> dict[str, Any]:
        doc: Document = context["document"]
        doc.transition(DocumentState.IN_REVIEW)

        decision = context.get("approval_decision", "approve")
        approver = ApproverActor()
        context["approver_id"] = context.get("approver_id", "approver_001")

        if decision == "approve":
            context = approver.perform("approve", context)
            print(f"     Document APPROVED by {context['approver_id']}.")
        elif decision == "reject":
            context["rejection_reason"] = context.get("rejection_reason", "Does not meet content standards.")
            context = approver.perform("reject", context)
            print(f"     Document REJECTED: {context['rejection_reason']}")
        else:
            raise NotImplementedError(f"ReviewDocument: unknown decision '{decision}'.")

        return context

    def on_error(self, context: dict[str, Any], error: Exception) -> dict[str, Any]:
        # GAP: If the approver system is unavailable, should review be suspended
        # and the document held in IN_REVIEW, or returned to SUBMITTED?
        raise NotImplementedError("ReviewDocument.on_error() is not implemented.")


class SetAccessPolicy(Step):
    """
    Access policy is defined for the document prior to publication.

    Determines who can see the document once published: PUBLIC, INTERNAL,
    RESTRICTED (specific groups), or CONFIDENTIAL (specific users).

    GAP: Who sets the access policy — the Author (at creation time),
    the Approver (as part of the approval decision), or the Admin
    (as a separate post-approval step)?  Currently assigned to Admin
    but this needs confirmation.

    GAP: How does the access policy integrate with the intranet's
    existing group/role management system?
    """

    actor = AdminActor
    inputs:  list[Type[DataObject]] = [Document]
    outputs: list[Type[DataObject]] = [Document, AccessPolicy]
    preconditions  = ["Document is in APPROVED state."]
    postconditions = [
        "An AccessPolicy object is attached to the document.",
        "Policy level is one of: PUBLIC, INTERNAL, RESTRICTED, CONFIDENTIAL.",
        "For RESTRICTED/CONFIDENTIAL, at least one group or user is specified.",
    ]
    description = "Admin (or Approver?) sets the access policy for the approved document."

    def handle(self, context: dict[str, Any]) -> dict[str, Any]:
        # GAP: Admin actor not yet implemented.
        raise NotImplementedError(
            "SetAccessPolicy.handle() — access policy assignment not yet implemented."
        )

    def on_error(self, context: dict[str, Any], error: Exception) -> dict[str, Any]:
        raise NotImplementedError("SetAccessPolicy.on_error() is not implemented.")


class PublishDocument(Step):
    """
    System publishes the approved document to the intranet.

    The document transitions to PUBLISHED state, is assigned a canonical URL,
    and the access policy is applied to the intranet's ACL system.
    Subscribers/followers are notified of the new publication.

    GAP: What is the notification strategy for publication?
      (a) All users in the allowed groups?
      (b) Only users who explicitly follow the document category?
      (c) A configurable subscription model?
    """

    actor = SystemActor
    inputs:  list[Type[DataObject]] = [Document, AccessPolicy]
    outputs: list[Type[DataObject]] = [Document, Notification]
    preconditions  = [
        "Document is in APPROVED state.",
        "An AccessPolicy is attached.",
        "Publishing user/system has 'publish' permission.",
    ]
    postconditions = [
        "Document is in PUBLISHED state.",
        "Document is accessible at its canonical URL.",
        "Access controls are enforced per the AccessPolicy.",
        "Relevant users have been notified.",
    ]
    description = "System publishes the document to the intranet with access controls applied."

    def handle(self, context: dict[str, Any]) -> dict[str, Any]:
        system = SystemActor()
        context = system.perform("publish", context)
        print(f"     Document PUBLISHED at {context.get('published_url', 'unknown URL')}.")

        # GAP: apply_access_policy not yet implemented
        # context = system.perform("apply_access_policy", context)
        return context

    def on_error(self, context: dict[str, Any], error: Exception) -> dict[str, Any]:
        # GAP: If publishing fails, should the document remain in APPROVED state
        # and be retried, or should an Admin be alerted?
        raise NotImplementedError("PublishDocument.on_error() is not implemented.")


# ---------------------------------------------------------------------------
# The Process
# ---------------------------------------------------------------------------

class DocumentApprovalProcess(Process):
    """
    End-to-end process for creating, approving, and publishing an intranet document.

    Flow:
      CreateDraft → EditAndFinaliseDraft → SubmitForApproval
        → ReviewDocument → [if approved] SetAccessPolicy → PublishDocument
        → [if rejected] EditAndFinaliseDraft (loop)

    Actors:   Author, Approver, Admin, System
    Objects:  Document, AccessPolicy, Notification

    Known gaps (see validate() for full list):
      - Approver assignment logic
      - 'Request changes' workflow state
      - Approval SLA and escalation path
      - Access policy ownership (Author vs Approver vs Admin)
      - Notification delivery mechanism
      - Rejection loop limit
      - Published document revision workflow
    """

    name = "Document Approval and Publishing Process"
    description = "Author creates → Approver reviews → Admin sets access → System publishes."

    def actors(self) -> list[Type[Actor]]:
        return [AuthorActor, ApproverActor, AdminActor, SystemActor]

    def steps(self) -> list[Type[Step]]:
        return [
            CreateDraft,
            EditAndFinaliseDraft,
            SubmitForApproval,
            ReviewDocument,
            SetAccessPolicy,
            PublishDocument,
        ]


# ===========================================================================
# Helpers
# ===========================================================================

def _is_not_implemented(cls: type, method_name: str) -> bool:
    """
    Return True if the named method's entire body is a bare ``raise NotImplementedError``.

    A method is considered "not implemented" only when its body (excluding any
    leading docstring) consists of exactly one statement that is an unconditional
    ``raise NotImplementedError(...)`` call.  Methods that raise NotImplementedError
    inside branches (e.g. ``else: raise NotImplementedError``) are considered
    implemented — the raise is a defensive guard, not a gap marker.
    """
    import ast

    method = getattr(cls, method_name, None)
    if method is None:
        return True
    try:
        src = inspect.getsource(method)
        src = textwrap.dedent(src)
        tree = ast.parse(src)
    except (OSError, TypeError, SyntaxError):
        return False

    func_def = next(
        (node for node in ast.walk(tree) if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))),
        None,
    )
    if func_def is None:
        return False

    # Strip leading docstring (an Expr node containing a constant)
    body = func_def.body
    if (
        body
        and isinstance(body[0], ast.Expr)
        and isinstance(body[0].value, ast.Constant)
    ):
        body = body[1:]

    if len(body) != 1 or not isinstance(body[0], (ast.Raise, ast.Pass)):
        return False

    if isinstance(body[0], ast.Pass):
        return True

    raise_node: ast.Raise = body[0]
    if raise_node.exc is None:
        return False

    exc = raise_node.exc
    # raise NotImplementedError or raise NotImplementedError(...)
    if isinstance(exc, ast.Call):
        func = exc.func
        return isinstance(func, ast.Name) and func.id == "NotImplementedError"
    if isinstance(exc, ast.Name):
        return exc.id == "NotImplementedError"
    return False


def _camel_to_label(name: str) -> str:
    """Convert CamelCase to 'Title Case With Spaces'."""
    import re
    return re.sub(r"(?<=[a-z])(?=[A-Z])", " ", name)


# ===========================================================================
# Entry point
# ===========================================================================

if __name__ == "__main__":
    process = DocumentApprovalProcess()

    # 1. Validate and report gaps
    process.validate()
    process.report()

    # 2. Show the step-based Mermaid diagram
    process.print_mermaid()

    # 3. Show the event-driven Mermaid diagram
    process.print_event_mermaid()

    # 4. Run with a mock context using the original sequential step execution
    mock_context = {
        "user_id":           "alice@example.com",
        "title":             "Q3 Engineering Update",
        "content":           "This quarter we shipped...",
        "approval_decision": "approve",
        "approver_id":       "bob@example.com",
    }
    process.run(mock_context)

    # 5. Run event-driven — approved path
    #    The process is started by publishing an initial event that simulates
    #    an external request arriving (e.g. a user clicking "New Document").
    print("--- Event-driven: approve path ---")
    event_context = {
        "user_id":           "alice@example.com",
        "title":             "Q4 Engineering Update",
        "content":           "This quarter we delivered...",
        "approval_decision": "approve",
        "approver_id":       "bob@example.com",
    }
    initial_event = Event(name="document_creation_requested", source="System")
    process.run_event_driven(initial_event, event_context)

    # 6. Run event-driven — rejection then re-approval path
    #    Demonstrates the event cycle: reject → author revises → re-submit → approve.
    print("--- Event-driven: reject then approve path ---")

    class DemoApprover(ApproverActor):
        """Approver that rejects on the first review and approves on the second."""
        def on_event(self, event: Event, bus: EventBus, context: dict[str, Any]) -> dict[str, Any]:
            review_count = context.get("review_count", 0) + 1
            context["review_count"] = review_count
            context["approval_decision"] = "reject" if review_count == 1 else "approve"
            if review_count == 2:
                context["revised_content"] = "Full revised content with expanded section 2."
            return super().on_event(event, bus, context)

    class DemoProcess(DocumentApprovalProcess):
        def actors(self) -> list[Type[Actor]]:
            return [AuthorActor, DemoApprover, AdminActor, SystemActor]

    demo = DemoProcess()
    reject_context = {
        "user_id":          "carol@example.com",
        "title":            "Annual Security Review",
        "content":          "Draft content — needs more detail.",
        "rejection_reason": "Content is too brief; please expand section 2.",
        "approver_id":      "dave@example.com",
    }
    demo.run_event_driven(Event(name="document_creation_requested", source="System"), reject_context)
